import { createSelector } from '@ngrx/store';

import * as fromXProfileInfo from './x-profile-info.reducer';
import {
  V2XProfileInfo_Loadeds,
  V2XProfileInfo_Errors,
  V2XProfileInfo_Datas,
} from './x-profile-info.interfaces';

/* ////////////////////////////////////////////////////////////////////////// */
/* Narrow selectors (Datas): Resolved (flat, via cacheKeyLatest)              */
/* ////////////////////////////////////////////////////////////////////////// */

/**
 * Select only the `data` data from the state.
 * Uses `cacheKeyLatest` to return data for the most recently dispatched call.
 * Only re-emits when the resolved data actually changes.
 */
export const selectDataData = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectDatas,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (datas, latestKeys, maskedKeys) => {
    if (maskedKeys?.has('data')) return undefined;
    const key = latestKeys['data'];
    return key ? datas.data[key] : undefined;
  },
);

/* ////////////////////////////////////////////////////////////////////////// */
/* Narrow selectors (Loadeds): Resolved (flat, via cacheKeyLatest)            */
/* ////////////////////////////////////////////////////////////////////////// */

/**
 * Select only the `data` loaded status.
 * Uses `cacheKeyLatest` to return the loaded status for the most recently
 * dispatched call.
 */
export const selectDataLoaded = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectLoadeds,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (loadeds, latestKeys, maskedKeys) => {
    if (maskedKeys?.has('data')) return undefined;
    const key = latestKeys['data'];
    return key ? loadeds.data[key] : undefined;
  },
);

/* ////////////////////////////////////////////////////////////////////////// */
/* Narrow selectors (Errors): Resolved (flat, via cacheKeyLatest)             */
/* ////////////////////////////////////////////////////////////////////////// */

/**
 * Select only the `data` error from the state.
 * Uses `cacheKeyLatest` to return the error for the most recently
 * dispatched call.
 */
export const selectDataError = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectErrors,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (errors, latestKeys, maskedKeys) => {
    if (maskedKeys?.has('data')) return undefined;
    const key = latestKeys['data'];
    return key ? errors.data[key] : undefined;
  },
);

/* ////////////////////////////////////////////////////////////////////////// */
/* Resolved (flat via cacheKeyLatest)                                         */
/* ////////////////////////////////////////////////////////////////////////// */

/**
 * Select all loadeds resolved to flat `{ [dataKey]?: boolean }`.
 * Uses `cacheKeyLatest` to resolve each key to its latest cache entry.
 *
 * NOTE: This selector is named `selectResolvedLoadeds` (not `selectLoadeds`)
 * because `selectLoadeds` is auto-generated by `createFeature()` and returns
 * the raw cache-keyed structure. The corresponding facade observable is named
 * `loadeds$` (not `resolvedLoadeds$`) for consumer convenience.
 */
export const selectResolvedLoadeds = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectLoadeds,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (loadeds, latestKeys, maskedKeys): V2XProfileInfo_Loadeds => {
    const result: V2XProfileInfo_Loadeds = {};
    for (const key of Object.keys(latestKeys)) {
      if (maskedKeys?.has(key)) continue;
      const ck = latestKeys[key];
      (result as any)[key] = ck ? loadeds[key]?.[ck] : undefined;
    }
    return result;
  },
);

/**
 * Select all errors resolved to flat `{ [dataKey]?: string }`.
 * Uses `cacheKeyLatest` to resolve each key to its latest cache entry.
 *
 * NOTE: This selector is named `selectResolvedErrors` (not `selectErrors`)
 * because `selectErrors` is auto-generated by `createFeature()` and returns
 * the raw cache-keyed structure. The corresponding facade observable is named
 * `errors$` (not `resolvedErrors$`) for consumer convenience.
 */
export const selectResolvedErrors = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectErrors,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (errors, latestKeys, maskedKeys): V2XProfileInfo_Errors => {
    const result: V2XProfileInfo_Errors = {};
    for (const key of Object.keys(latestKeys)) {
      if (maskedKeys?.has(key)) continue;
      const ck = latestKeys[key];
      (result as any)[key] = ck ? errors[key]?.[ck] : undefined;
    }
    return result;
  },
);

/**
 * Select all datas resolved to flat `{ [dataKey]?: Type }`.
 * Uses `cacheKeyLatest` to resolve each key to its latest cache entry.
 *
 * NOTE: This selector is named `selectResolvedDatas` (not `selectDatas`)
 * because `selectDatas` is auto-generated by `createFeature()` and returns
 * the raw cache-keyed structure. The corresponding facade observable is named
 * `datas$` (not `resolvedDatas$`) for consumer convenience.
 */
export const selectResolvedDatas = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectDatas,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheKeyLatest,
  fromXProfileInfo.v2XProfileInfoFeature.selectCacheMaskedKeys,
  (datas, latestKeys, maskedKeys): V2XProfileInfo_Datas => {
    const result: V2XProfileInfo_Datas = {};
    for (const key of Object.keys(latestKeys)) {
      if (maskedKeys?.has(key)) continue;
      const ck = latestKeys[key];
      (result as any)[key] = ck ? datas[key]?.[ck] : undefined;
    }
    return result;
  },
);

/* ////////////////////////////////////////////////////////////////////////// */
/* Computed                                                                    */
/* ////////////////////////////////////////////////////////////////////////// */

/**
 * Compute to see if there are any `errors` in the state.
 * Returns `true` if there's at least one error across all cache entries,
 * otherwise `false`.
 *
 * @type {boolean}
 */
export const selectHasError = createSelector(
  fromXProfileInfo.v2XProfileInfoFeature.selectErrors,
  (errors) => {
    return Object.values(errors).some((errorRecord) =>
      Object.values(errorRecord).some((e) => e !== undefined),
    );
  },
);
