require_relative '../../../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.3/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.3/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.3/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.pnpm/@capacitor+app@7.1.0_@capacitor+core@7.4.3/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../../node_modules/.pnpm/@capacitor+app-launcher@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../../../node_modules/.pnpm/@capacitor+browser@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/browser'
  pod 'CapacitorDevice', :path => '../../../../node_modules/.pnpm/@capacitor+device@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/.pnpm/@capacitor+filesystem@7.1.4_@capacitor+core@7.4.3/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/.pnpm/@capacitor+haptics@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.pnpm/@capacitor+keyboard@7.0.3_@capacitor+core@7.4.3/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.pnpm/@capacitor+preferences@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/.pnpm/@capacitor+push-notifications@7.0.3_@capacitor+core@7.4.3/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/.pnpm/@capacitor+share@7.0.2_@capacitor+core@7.4.3/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.pnpm/@capacitor+status-bar@7.0.3_@capacitor+core@7.4.3/node_modules/@capacitor/status-bar'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+analytics@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorFirebaseAuthentication', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+authentication@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorFirebaseCrashlytics', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+crashlytics@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/crashlytics'
  pod 'CapacitorFirebaseFirestore', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+firestore@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/firestore'
  pod 'CapacitorFirebaseRemoteConfig', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+remote-config@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/remote-config'
  pod 'CapacitorPluginAppTrackingTransparency', :path => '../../../../node_modules/.pnpm/capacitor-plugin-app-tracking-transparency@2.0.5_@capacitor+core@7.4.3/node_modules/capacitor-plugin-app-tracking-transparency'
  pod 'CapawesomeCapacitorLiveUpdate', :path => '../../../../node_modules/.pnpm/@capawesome+capacitor-live-update@7.2.2_@capacitor+core@7.4.3/node_modules/@capawesome/capacitor-live-update'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'FirebaseMessaging'

  # https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/analytics#ios
  # NOTE: Shall we have `AnalyticsWithoutAdIdSupport` or `Analytics`? Well, 
  # `AnalyticsWithoutAdIdSupport` is required, if you're NOT going to show ads 
  # in your app by using Google AdMob or other ad networks; and `Analytics` is
  # required, if you are going to show ads in your app :)
  # NOTE: If you're going to add the Pod by an automation tool, feel free to
  # comment the Pod that is added manually here.
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+analytics@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/analytics'
  # pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+analytics@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/analytics'

  # NOTE: If you're going to add the Pod by an automation tool, feel free to
  # comment the Pod that is added manually here.
  pod 'CapacitorFirebaseAuthentication/Google', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+authentication@7.3.1_@capacitor+core@7.4.3_firebase@12.2.1/node_modules/@capacitor-firebase/authentication'
end

pre_install do |installer|
  podfile = File.read(File.basename(__FILE__))

  # Find path for CapacitorFirebaseAnalytics
  if podfile =~ /pod\s+'CapacitorFirebaseAnalytics',\s+:path\s=>\s+'([^']+)'/
    analytics_path = $1

    # replace the path for AnalyticsWithoutAdIdSupport based on found analytics_path
    modified_podfile = podfile.gsub(
      /(#[\t\s]*pod\s+'CapacitorFirebaseAnalytics\/AnalyticsWithoutAdIdSupport',[\t\s]*:path[\t\s]*=>[\t\s]*'[^']+')/,
      "  pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '#{analytics_path}'"
    )

    # Write back the updated Podfile
    File.write(File.basename(__FILE__), modified_podfile)
  end
end


post_install do |installer|
  assertDeploymentTarget(installer)

  # Below will make sure third-party libs are not signed
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
