require_relative '../../../../node_modules/.pnpm/@capacitor+ios@6.2.1_@capacitor+core@6.2.1/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.2.1_@capacitor+core@6.2.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.2.1_@capacitor+core@6.2.1/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.pnpm/@capacitor+app@6.0.2_@capacitor+core@6.2.1/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../../node_modules/.pnpm/@capacitor+app-launcher@6.0.3_@capacitor+core@6.2.1/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../../../node_modules/.pnpm/@capacitor+browser@6.0.5_@capacitor+core@6.2.1/node_modules/@capacitor/browser'
  pod 'CapacitorDevice', :path => '../../../../node_modules/.pnpm/@capacitor+device@6.0.2_@capacitor+core@6.2.1/node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/.pnpm/@capacitor+filesystem@6.0.3_@capacitor+core@6.2.1/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/.pnpm/@capacitor+haptics@6.0.2_@capacitor+core@6.2.1/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.pnpm/@capacitor+keyboard@6.0.3_@capacitor+core@6.2.1/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.pnpm/@capacitor+preferences@6.0.3_@capacitor+core@6.2.1/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/.pnpm/@capacitor+push-notifications@6.0.4_@capacitor+core@6.2.1/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/.pnpm/@capacitor+share@6.0.3_@capacitor+core@6.2.1/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.pnpm/@capacitor+status-bar@6.0.2_@capacitor+core@6.2.1/node_modules/@capacitor/status-bar'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+analytics@6.3.1_@capacitor+core@6.2.1_firebase@10.14.1/node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorFirebaseRemoteConfig', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+remote-config@6.3.1_@capacitor+core@6.2.1_firebase@10.14.1/node_modules/@capacitor-firebase/remote-config'
  pod 'CapacitorPluginAppTrackingTransparency', :path => '../../../../node_modules/.pnpm/capacitor-plugin-app-tracking-transparency@2.0.5_@capacitor+core@6.2.1/node_modules/capacitor-plugin-app-tracking-transparency'
end

target 'App' do
  capacitor_pods
  # Add manual Pods here
  pod 'FirebaseMessaging'

  # pre_install will update the path value and uncomment this line.
  # It is important to keep this line commented to begin with or the
  # Ruby script is not able to edit it  - I don't know why but this works and it's fine -
  # If running locally and versions don't match, simply comment the below line and allow
  # the Ruby script fix it for you.
#   pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+analytics@6.3.1_@capacitor+core@6.2.1_firebase@10.14.1/node_modules/@capacitor-firebase/analytics'
end

pre_install do |installer|
  podfile = File.read(File.basename(__FILE__))

  # Find path for CapacitorFirebaseAnalytics
  if podfile =~ /pod\s+'CapacitorFirebaseAnalytics',\s+:path\s=>\s+'([^']+)'/
    analytics_path = $1

    # replace the path for AnalyticsWithoutAdIdSupport based on found analytics_path
    modified_podfile = podfile.gsub(
      /(#[\t\s]*pod\s+'CapacitorFirebaseAnalytics\/AnalyticsWithoutAdIdSupport',[\t\s]*:path[\t\s]*=>[\t\s]*'[^']+')/,
      "  pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '#{analytics_path}'"
    )

    # Write back the updated Podfile
    File.write(File.basename(__FILE__), modified_podfile)
  end
end


post_install do |installer|
  assertDeploymentTarget(installer)

  # Below will make sure third-party libs are not signed
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
